highlighter: 'pygments'
safe: true
exclude: [node_modules]

github:
  url: http://localhost:4000
  owner_gravatar_url: images/avatar.png
  zip_url: https://github.com/github/metadata-example/zipball/gh-pages
  clone_url: https://github.com/github/metadata-example.git
  repository_url: https://github.com/github/metadata-example
  project_tagline: Frizz Free, Environment-aware, JavaScript Modules